### ISSUE TITLE
Melhorias no GitPages

### ISSUE THREAD

**Issue by pedrohelias** [Interacao-Humano-Computador/2021.2-Grupo-05-Yale#9]
### Todos realizam

- [x] @aluzianobriceno - Métodos de Design(Adição de conteúdo e revisão).

- [x] @Maiconrq - Melhorias no cronograma + modernização.

- [x] @CDGodoy - Ferramentas utilizadas no projeto

- [x] @lramon2001 - Modernização da Home do site (Introdução + Breve resumo do site que vamos trabalhar)

- [x] @Luiz-GL-Campos  - prints das páginas do site com a data que foram capturadas + justificativas do por quê vamos trabalhar com o site

- [x] @pedrohelias - Melhorias nas políticas, adição dos conteúdos referentes a metodologia + justificativa sobre métodos SCRUM e KAMBAN

### Prazo para entrega: Até 23h59 do dia 21/02/2022
